# Generated by Django 5.2.1 on 2025-05-28 17:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('c6537dd0-0cee-4fdc-921f-ad52e169bf86'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
